#pragma once
namespace GarageCatalog {
struct Entry {const char* id;const char* family;const char* variant;int category;};
inline constexpr Entry Entries[]={
    {"MarsRover1","Test rover","Style 1",4},
    {"EDF_APC-A_1","EDF APC","MG 1",2},
    {"EDF_APC-A_2","EDF APC","MG 2",2},
    {"EDF_APC-A_3","EDF APC","MG 3",2},
    {"EDF_APC-A_4","EDF APC","MG 4",2},
    {"EDF_APC-A_Gauss","EDF APC","Gauss 1",2},
    {"EDF_APC-A_Gauss2","EDF APC","Gauss 2",2},
    {"EDF_APC-A_Gauss3","EDF APC","Gauss 3",2},
    {"EDF_APC-A_Gauss4","EDF APC","Gauss 4",2},
    {"EDF_APC_noturret","EDF APC","Unarmed 1",2},
    {"EDF_APC_noturret2","EDF APC","Unarmed 2",2},
    {"EDF_APC_noturret3","EDF APC","Unarmed 3",2},
    {"EDF_APC_noturret4","EDF APC","Unarmed 4",2},
    {"EDF_Scout_1","EDF Scout","MG 1",2},
    {"EDF_Scout_2","EDF Scout","MG 2",2},
    {"EDF_Scout_3","EDF Scout","MG 3",2},
    {"EDF_Scout_4","EDF Scout","MG 4",2},
    {"EDF_Scout_Gauss","EDF Scout","Gauss 1",2},
    {"EDF_Scout_Gauss2","EDF Scout","Gauss 2",2},
    {"EDF_Scout_Gauss3","EDF Scout","Gauss 3",2},
    {"EDF_Scout_Gauss4","EDF Scout","Gauss 4",2},
    {"EDF_ScoutNoTurret","EDF Scout","Unarmed 1",2},
    {"EDF_ScoutNTurret2","EDF Scout","Unarmed 2",2},
    {"EDF_ScoutNTurret3","EDF Scout","Unarmed 3",2},
    {"Walker_Civilian","Heavy walker","Style 1",3},
    {"Walker_Civilian2","Heavy walker","Style 2",3},
    {"Walker_Civilian3","Heavy walker","Style 3",3},
    {"Mar_Jetter_1","Marauder Jetter","Style 1",5},
    {"Mar_Raider_1","Marauder Raider","Harpoon 1",5},
    {"Col_FixedFlatbed_2","Flatbed","Rockets 1",1},
    {"EDF_HeavyTank-A_1","Heavy tank","Cannon 1",2},
    {"Civ_ResRunner_1","Supercar","Style 1",0},
    {"Civ_ResRunner-C_1","Luxury coupe","Style 1",0},
    {"Civ_ResLuxury-C_1","Luxury SUV","Style 1",0},
    {"Col_Taxi_1","Taxi","Style 1",0},
    {"Col_Taxi_2","Taxi","Style 2",0},
    {"Col_Taxi_3","Taxi","Style 3",0},
    {"Col_Caravan_1","Bus","Style 1",1},
    {"Col_Caravan_2","Bus","Style 2",1},
    {"Col_Caravan_3","Bus","Style 3",1},
    {"Col_Mini_Hauler_1","Mini hauler","Style 1",5},
    {"Col_Mini_Hauler_2","Mini hauler","Style 2",5},
    {"Col_Mini_Hauler_3","Mini hauler","Style 3",5},
    {"EDF_ScoutNTurret4","EDF Scout","Unarmed 4",2},
    {"EDF_StaffCar_1","EDF staff car","MG 1",2},
    {"Min_ATV_1","Mining ATV","Style 1",5},
    {"Min_ATV_2","Mining ATV","Style 2",5},
    {"Min_ATV_3","Mining ATV","Style 3",5},
    {"Min_ATV_MG1","Mining ATV","MG 1",5},
    {"Min_ATV_MG2","Mining ATV","MG 2",5},
    {"Min_ATV_MG3","Mining ATV","MG 3",5},
    {"Min_LightPickup_1","Light pickup","Style 1",5},
    {"Min_LightPickup_2","Light pickup","Style 2",5},
    {"Min_LightPickup_3","Light pickup","Style 3",5},
    {"Min_LightPickup_MG1","Light pickup","MG 1",5},
    {"Min_LightPickup_MG2","Light pickup","MG 2",5},
    {"Min_LightPickup_MG3","Light pickup","MG 3",5},
    {"Min_Rover-A_1","Mining rover","Style 1",5},
    {"Min_Rover-A_2","Mining rover","Style 2",5},
    {"Min_Rover-A_3","Mining rover","Style 3",5},
    {"Min_Rover-A_MG1","Mining rover","MG 1",5},
    {"Min_Rover-A_MG2","Mining rover","MG 2",5},
    {"Min_Rover-A_MG3","Mining rover","MG 3",5},
    {"Min_Rover-A_DMG1","Mining rover","Dual MG 1",5},
    {"Min_Rover-A_DMG2","Mining rover","Dual MG 2",5},
    {"Min_Rover-A_DMG3","Mining rover","Dual MG 3",5},
    {"Min_Rover-A_DRR1","Mining rover","Rockets 1",5},
    {"Min_Rover-A_DRR2","Mining rover","Rockets 2",5},
    {"Min_Rover-A_DRR3","Mining rover","Rockets 3",5},
    {"Min_Emergency_1","Emergency rover","Style 1",0},
    {"Min_Jetter_1","Jetter","Rockets 1",0},
    {"Min_SupplyTruck_1","Supply truck","Style 1",1},
    {"EDF_AAXAir_1","AI gunship","Style 1",4},
    {"EDF_StaffCar_2","EDF staff car","MG 2",2},
    {"EDF_StaffCar_3","EDF staff car","MG 3",2},
    {"EDF_StaffCar_Gauss","EDF staff car","Gauss 1",2},
    {"EDF_StaffCar_Gauss2","EDF staff car","Gauss 2",2},
    {"EDF_StaffCar_Gauss3","EDF staff car","Gauss 3",2},
    {"EDF_StaffCar_NoTurret","EDF staff car","Unarmed 1",2},
    {"Min_SupplyTruck_RT","Supply truck","RT variant 1",1},
    {"EDF_HeavyTank-A_2","Heavy tank","Cannon 2",2},
    {"EDF_HeavyTank-A_3","Heavy tank","Cannon 3",2},
    {"EDF_HeavyTank-A_4","Heavy tank","Cannon 4",2},
    {"EDF_MediumTank-A_1","Medium tank","Cannon 1",2},
    {"EDF_AAXAir_2","AI gunship","Rockets 1",4},
    {"EDF_StaffCar_NTurret3","EDF staff car","Unarmed 3",2},
    {"EDF_StaffCar_NTurret2","EDF staff car","Unarmed 2",2},
    {"EDF_Supplytruck_1","EDF supply","MG 1",1},
    {"EDF_ABXAir_1","AI bomber","Style 1",4},
    {"Tharsis_gun","Tharsis gun","Style 1",4},
    {"EDF_Scout_Rocket","EDF Scout","Special 1",2},
    {"EDF_AAXAir_Gauss","AI gunship","Gauss 1",4},
    {"Walker_Min","Light walker","Style 1",3},
    {"Min_SupplyTruck_2","Supply truck","Style 2",1},
    {"Min_SupplyTruck_3","Supply truck","Style 3",1},
    {"Walker_Min2","Light walker","Style 2",3},
    {"Walker_Min3","Light walker","Style 3",3},
    {"Walker_Flamer","Combat walker","Rockets 1",3},
    {"EDF_MediumTank-A_2","Medium tank","Cannon 2",2},
    {"EDF_MediumTank-A_3","Medium tank","Cannon 3",2},
    {"EDF_ArtTank_1","Artillery tank","Cannon 1",2},
    {"EDF_Supplytruck_2","EDF supply","MG 2",1},
    {"EDF_Supplytruck_3","EDF supply","MG 3",1},
    {"EDF_Supplytruck_Gauss","EDF supply","Gauss 1",1},
    {"EDF_Supplytruck_Gauss2","EDF supply","Gauss 2",1},
    {"EDF_Supplytruck_Gauss3","EDF supply","Gauss 3",1},
    {"EDF_Supplytruck_NoTurret","EDF supply","Unarmed 1",1},
    {"EDF_Supplytruck_NTurret2","EDF supply","Unarmed 2",1},
    {"EDF_Supplytruck_NTurret3","EDF supply","Unarmed 3",1},
    {"Min_SupplyTruck_MG1","Supply truck","Rockets 1",1},
    {"Min_SupplyTruck_MG2","Supply truck","Rockets 2",1},
    {"Min_SupplyTruck_MG3","Supply truck","Rockets 3",1},
    {"Col_TrashTruck_MG1","Garbage truck","Rockets 1",1},
    {"Col_TrashTruck_1","Garbage truck","Style 1",1},
    {"Min_DumpTruck_1","Dump truck","Style 1",1},
    {"Min_DumpTruck_2","Dump truck","Style 2",1},
    {"Min_DumpTruck_3","Dump truck","Style 3",1},
    {"Min_Bulldozer_1","Bulldozer","Style 1",4},
    {"Col_FuelTanker_1","Fuel tanker","Style 1",1},
    {"Col_FuelTanker_2","Fuel tanker","Style 2",1},
    {"Col_FuelTanker_3","Fuel tanker","Style 3",1},
    {"Col_FixedFlatbed","Flatbed","Style 1",1},
    {"Col_FixedFlatbed2","Flatbed","Style 2",1},
    {"Col_FixedFlatbed3","Flatbed","Style 3",1},
    {"Min_Rover-A_1WK","Mining rover","WC 1",5},
    {"Min_Rover-A_2WK","Mining rover","WC 2",5},
    {"Min_Rover-A_3WK","Mining rover","WC 3",5},
    {"EDF_StaffCar_H2H","EDF staff car","HM Gauss 1",2},
    {"EDF_MediumTank-A_4","Medium tank","Cannon 4",2},
    {"EDF_ArtTank_2","Artillery tank","Gauss 2",2},
};
}

